### ISSUE TITLE
MSVC not supported

### ISSUE THREAD

**Issue by VSRonin** [crapp/qaccordion#1]
CMakeLists does not support MSVC compiler

in

```
# Compiler-specific C++11 activation.
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
    execute_process(
        COMMAND ${CMAKE_CXX_COMPILER} -dumpversion OUTPUT_VARIABLE GCC_VERSION)
    if (NOT (GCC_VERSION VERSION_GREATER 4.7 OR GCC_VERSION VERSION_EQUAL 4.7))
        message(FATAL_ERROR "${PROJECT_NAME} requires g++ 4.7 or greater.")
    endif ()
elseif ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    if (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libstdc++")
    elseif (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
    endif()
else ()
    message(FATAL_ERROR "Your C++ compiler does not support C++11.")
endif ()
```

add an else for MSVC (also I think you need to unquote the variables), it needs no additional flags.

second thing:
add the configuration of the output to [NMake Makefiles](https://cmake.org/Wiki/CMake_Generator_Specific_Information) otherwise it will generate unusable project files instead of makefiles

In alternative, include the classic .pro files that can be used with qmake

**Comment by crapp** [comment]
Thanks for bringing this to my attention! I have to admit windows support wasn't tested before :) I did fix the CMake config files. It should be possible now to build the project. But there is another problem I am currently working on. I just had the demo application running on Windows. I will test the code a bit more and then push it to github.

**Comment by VSRonin** [comment]
Not 100% sure it fixes it.
Symbols are not exported due to missing __declspec( dllexport ) and __declspec( dllimport )
See my comments in commit

**Comment by crapp** [comment]
Hi Luca, 

finally found some time to respond and push my changes. The Bug was closed automatically as I referenced it in in the first commit, so this might have been a bit misleading to you. 

I tested the library on Windows now and the new CMake configuration works with MSVC (both Visual Studio and NMake). I have added a section in the README with instructions. The lack of support for MinGW is intentional. My MinGW knowledge is minimal although I developed Windows Software for the last 5 years. Bu this was done either with C# or MSVC + C++. You are welcome to test the library on Windows with MinGW and make a pull request with an updated cmake configuration. I am currently focusing on new features. 

Thanks again for your valuable input!
